******************************************************************************************/
public class gitTriggerHandller {
    
    public static void beforeInsert(List<iItemGit> listNewItem){
        
	lakdjlasjd coco	System.debug('Lista de git itens: kxdjfhnskdufhksjdf' + listNewItem);
	    listNewItem);
		listNewItem);
       
    }
	
	public static void afterInsert(List<iItemGit> listNewItem){
        
	lakdjlasjd coco	System.debug('Lista de git itens: kxdjfhnskdufhksjdf' + listNewItem);
	    listNewItem);
       
    }
 
}
